# render.yaml
services:
  - type: web
    name: ankitai
    env: static
    plan: free
    repo: https://github.com/eddiebrock911/profile # GitHub repo link
    branch: main
    buildCommand: ""      # Static site ke liye kuch build nahi karna
    staticPublishPath: /
    autoDeploy: true
